POST http://localhost:8080/time
Content-Type: application/json

{
  "students": [
    "nr_indeksu1",
    "nr_indeksu2"
  ],
  "received_time": "<to co przyszło z MQTT>"
}

###
GET http://localhost:8080/time?tz=+3

###
